# Site settings
title: Jamstatic
email: contact@jamstatic.fr
description: Communauté francophone des utilisateurs de générateurs de site statique
baseurl: ""
permalink: /:year/:month/:day/:title/
timezone: Europe/Paris
lang: fr

repository: jekyll-fr/jekyll-fr.github.io
branch: source

twitter:
  username: jamstatic_fr
github:
  username: jekyll-fr

social:
  type: organization
  links:
    - https://twitter.com/jamstatic_fr
    - https://github.com/jekyll-fr

analytics:
  google:
    tracking_id: UA-75833986-1

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

gist:
  noscript: false

exclude:
  - .editorconfig
  - .gitignore
  - .forestryio
  - .rubocop.yml
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - script

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      image: /assets/images/logo-2x.png

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-gist
  - jemoji
