---
title: Jamstatic
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    author: Frank Taillandier
    image: "/assets/images/logo-2x.png"
email: contact@jamstatic.fr
description: L'actualité autour des générateurs de site statique et de la JAMStack
url: https://jamstatic.fr
baseurl: 
permalink: "/:year/:month/:day/:title/"
lang: fr
repository: jamstatic/jamstatic-fr
branch: master
twitter:
  username: jamstatic_fr
github:
  username: jamstatic
social:
  type: organization
  links:
  - https://twitter.com/jamstatic_fr
  - https://github.com/jamstatic
analytics:
  google:
    tracking_id: UA-75833986-1
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
livereload: true
exclude:
- ".editorconfig"
- ".forestryio"
- ".gitignore"
- ".rubocop.yml"
- ".travis.yml"
- Gemfile
- Gemfile.lock
- LICENSE
- Rakefile
- README.md
- script
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
