---
new_page_extension: md
auto_deploy: false
admin_path: static/redac
webhook_url: ''
sections:
- type: directory
  path: content/post
  label: Articles
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: config.yaml
  label: Configuration
upload_dir: ''
public_path: ''
front_matter_path: https://res.cloudinary.com/jamstatic/image/upload/c_scale,f_auto,q_auto,w_1200
use_front_matter_path: true
file_template: 'https://res.cloudinary.com/jamstatic/image/upload/c_scale,f_auto,q_auto,w_1028/:filename:'
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.55.6
