---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: content/post
  label: Articles
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: data/authors.yml
  label: Authors
upload_dir: bgmf
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.52
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.52
  preview_output_directory: public
  output_directory: public
version: '0.52'
