baseURL: https://jamstatic.fr
enableRobotsTXT: true
disqusShortname: jekyllfr

theme: "json-api"

build:
  useResourceCacheWhen: never
  writeStats: true

outputs:
  home:
    - html
    - rss
    - jsonfeed
    - json
    - HEADERS
    - REDIR
    - algolia
  page:
    - html
    - json

outputFormats:
  algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  rss:
    baseName: "feed"
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  HEADERS:
    mediaType: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true
  REDIR:
    mediaType: "text/netlify"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true
